---
title: "Viz and EDA"
#Talea Cornelius
#09/23/2020
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load packages}
library(tidyverse)
library(ggridges)
```
```{r load data}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

```{r basic scatterplot}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r plot using pipe}
#Useful for processing data without saving intermediate data steps

weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
#You can also save the output of ggplot() to an object and modify / print it later. This is often helpful, although it’s not my default approach to making plots.

plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()
```

```{r add colors}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r add curve, points transparency}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

```{r}
#The X and Y mappings apply to the whole graphic, but color is currently geom-specific

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r change x axis}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```
```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(tmax_fahr = tmax * (9 / 5) + 32,
         tmin_fahr = tmin * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)
```

```{r no points}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
#argument to geom_point
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")

#implicitly creating a new variable "color" that applies to all datapoints
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```

```{r histogram}
ggplot(weather_df, aes(x = tmax)) + 
  geom_histogram()
```

```{r}
#The position = "dodge" places the bars for each group side-by-side

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```
```{r density plots}
#The adjust parameter in density plots is similar to the binwidth parameter in histograms
#I set the transparency level to .4 to make sure all densities appear
#You should also note the distinction between fill and color aesthetics here. You could facet by name as above but would have to ask if that makes comparisons easier or harder. 
#Adding geom_rug() to a density plot can be a helpful way to show the raw data in addition to the density.

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue") +
geom_rug()
```

```{r boxplot}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()
```

```{r violin plots}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)
```

```{r ridge plots}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

```{r}
ggplot(weather_df, aes(x = prcp)) + 
  geom_density(aes(fill = name), alpha = .5) 

#Next a ridge plot:

ggplot(weather_df, aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)

#Last a boxplot:

ggplot(weather_df, aes(y = prcp, x = name)) + 
  geom_boxplot() 

# This is a tough variable to plot because of the highly skewed distribution in each location. Of these, I’d probably choose the boxplot because it shows the outliers most clearly. If the “bulk” of the data were interesting, I’d probably compliment this with a plot showing data for all precipitation less than 100, or for a data omitting days with no precipitation.

weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)
```

```{r save plot}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```


```{r adjust figure size in knit Rmd file}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```
















